# -*- coding: utf-8 -*-
{
    'name': "BSTT Finger Print",
    'version': "18.0.1.0.0",
    'summary': "Enhanced BSTT Finger Print module",
    'description': "Enhanced BSTT Finger Print module for Odoo 18.0 by roottbar",
    'category': "accounting",
    'author': "BSTT company",
    'maintainer': "roottbar",
    'depends': [
        'base',
        'mail',
        'hr',
        'resource',
        'hr_attendance',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/cron.xml',
        'views/server_configuration_views.xml',
        'views/hr_employee.xml',
        'views/attendance_data.xml',
        'views/resource_views.xml',
        'views/hr_attendance_view.xml',
        'wizard/reinsert_into_hr_attendance.xml',
    ],
    'license': "LGPL-3",
    'installable': True,
    'auto_install': False,
}
