# -*- coding: utf-8 -*-
{
    'name': "Rent Customization",
    'version': "18.0.1.0.0",
    'summary': "Enhanced Rent Customization module",
    'description': "Enhanced Rent Customization module for Odoo 18.0 by roottbar",
    'category': "Tools",
    'author': "Ibrahim Abdullatif",
    'maintainer': "roottbar",
    'depends': [
        'base',
        'sale_renting',
        'sale_operating_unit',
        'analytic',
        'account_asset',
        'l10n_gcc_invoice',
        'product',
    ],
    'data': [
        'views/vw_menu_items.xml',
        'views/vw_rent_account_move_inherit.xml',
        'views/vw_rent_config_property_types.xml',
        'views/vw_rent_config_property_purposes.xml',
        'views/vw_rent_config_property_maintenance_types.xml',
        'views/vw_rent_config_property_maintenance_statuses.xml',
        'views/vw_rent_config_unit_finishes.xml',
        'views/vw_rent_config_unit_maintenance_types.xml',
        'views/vw_rent_config_unit_maintenance_statuses.xml',
        'views/vw_rent_config_unit_overlooks.xml',
        'views/vw_rent_config_unit_types.xml',
        'views/vw_rent_maintenance_pivot_report.xml',
        'views/vw_rent_config_unit_purposes.xml',
        'views/vw_rent_res_partner_inherit.xml',
        'views/vw_rent_product_inherit.xml',
        'views/vw_rent_product.xml',
        'views/vw_rent_property.xml',
        'views/vw_rent_property_elevator.xml',
        'views/vw_rent_property_maintenance.xml',
        'views/vw_rent_unit_maintenance.xml',
        'views/vw_rent_sale_order_inherit.xml',
        'views/vw_rent_sale_order_lines.xml',
        'views/vw_rent_units_report_wizard.xml',
        'views/vw_product_configuration.xml',
        'report/reports.xml',
        'report/rent_units_report_template.xml',
        'data/demo_products.xml',
        'security/renting_security.xml',
        'security/ir.model.access.csv',
    ],
    'license': "LGPL-3",
    'application': True,
    'installable': True,
    'auto_install': False,
}