# -*- coding: utf-8 -*-
{
    'name': "Account Financial Reports",
    'version': "18.0.1.0.0",
    'summary': "Enhanced Account Financial Reports module",
    'description': "Enhanced Account Financial Reports module for Odoo 18.0 by roottbar",
    'category': "Reporting",
    'author': "Camptocamp,initOS GmbH,redCOR AG,ForgeFlow,Tecnativa,Odoo Community Association (OCA)",
    'maintainer': "roottbar",
    'depends': [
        'base',
        'account',
        'date_range',
        'report_xlsx',
    ],
    'data': [
        'data/report_column_data.xml',
        'security/ir.model.access.csv',
        'security/security.xml',
        'wizard/aged_partner_balance_wizard_view.xml',
        'wizard/general_ledger_wizard_view.xml',
        'wizard/journal_ledger_wizard_view.xml',
        'wizard/open_items_wizard_view.xml',
        'wizard/trial_balance_wizard_view.xml',
        'wizard/vat_report_wizard_view.xml',
        'view/account_age_report_configuration_views.xml',
        'menuitems.xml',
        'reports.xml',
        'report/templates/layouts.xml',
        'report/templates/aged_partner_balance.xml',
        'report/templates/general_ledger.xml',
        'report/templates/journal_ledger.xml',
        'report/templates/open_items.xml',
        'report/templates/trial_balance.xml',
        'report/templates/vat_report.xml',
        'view/account_view.xml',
        'view/account_financial_report_column_view.xml',
        'view/report_general_ledger.xml',
        'view/report_journal_ledger.xml',
        'view/report_trial_balance.xml',
        'view/report_open_items.xml',
        'view/report_aged_partner_balance.xml',
        'view/report_vat_report.xml',
        'view/res_config_settings_views.xml',
    ],
    'license': "LGPL-3",
    'application': True,
    'installable': True,
    'auto_install': False,
}