# -*- coding: utf-8 -*-
{
    'name': "Ejar Platform Integration",
    'version': "18.0.1.0.0",
    'summary': "Enhanced Ejar Platform Integration module",
    'description': "Enhanced Ejar Platform Integration module for Odoo 18.0 by roottbar",
    'category': "Real Estate",
    'author': "Ibrahim Abdullatif",
    'maintainer': "roottbar",
    'depends': [
        'base',
        'renting',
        'sale_renting',
        'sale_operating_unit',
        'analytic',
        'account_asset',
        'l10n_gcc_invoice',
        'product',
        'einv_sa',
        'contacts',
        'mail',
        'portal',
    ],
    'data': [
        'security/ejar_security.xml',
        'security/ir.model.access.csv',
        'data/ejar_data.xml',
        'views/ejar_menu.xml',
        'views/ejar_property_views.xml',
        'views/ejar_contract_views.xml',
        'views/ejar_tenant_views.xml',
        'views/ejar_landlord_views.xml',
        'views/ejar_sync_log_views.xml',
        'views/ejar_dashboard_views.xml',
    ],
    'license': "LGPL-3",
    'application': True,
    'installable': True,
    'auto_install': False,
}