# -*- coding: utf-8 -*-
{
    'name': "Dashboard Ninja",
    'version': "18.0.1.0.0",
    'summary': "Enhanced Dashboard Ninja module",
    'description': "Enhanced Dashboard Ninja module for Odoo 18.0 by roottbar",
    'category': "Tools",
    'author': "Ksolves India Ltd.",
    'maintainer': "roottbar",
    'depends': [
        'base',
        'web',
        'base_setup',
        'bus',
    ],
    'assets': {
        'web.assets_backend': [
            'ks_dashboard_ninja/static/src/js/ks_boot.js',
            'ks_dashboard_ninja/static/src/css/ks_dashboard_gridstack.css',
            'ks_dashboard_ninja/static/src/css/ks_dashboard_item_theme.css',
            'ks_dashboard_ninja/static/src/css/ks_dashboard_ninja_item.css',
            'ks_dashboard_ninja/static/src/css/ks_dashboard_ninja_pro.css',
            'ks_dashboard_ninja/static/src/css/ks_dashboard_options.css',
            'ks_dashboard_ninja/static/src/css/ks_dn_filter.css',
            'ks_dashboard_ninja/static/src/css/ks_icon_container_modal.css',
            'ks_dashboard_ninja/static/src/css/ks_to_do_item.css',
            'ks_dashboard_ninja/static/src/css/ks_toggle_icon.css',
            'ks_dashboard_ninja/static/src/scss/ks_dn_gridstack.scss',

            'ks_dashboard_ninja/static/src/js/ks_color_picker.js',
            'ks_dashboard_ninja/static/src/js/ks_dashboard_item_theme.js',
            'ks_dashboard_ninja/static/src/js/ks_dashboard_ninja.js',
            'ks_dashboard_ninja/static/src/js/ks_dashboard_ninja_graph_preview.js',
            'ks_dashboard_ninja/static/src/js/ks_dashboard_ninja_item_preview.js',
            'ks_dashboard_ninja/static/src/js/ks_dashboard_ninja_kpi_preview.js',
            'ks_dashboard_ninja/static/src/js/ks_dashboard_ninja_list_view_preview.js',
            'ks_dashboard_ninja/static/src/js/ks_date_picker.js',
            'ks_dashboard_ninja/static/src/js/ks_domain_fix.js',
            'ks_dashboard_ninja/static/src/js/ks_filter_props.js',
            'ks_dashboard_ninja/static/src/js/ks_global_functions.js',
            'ks_dashboard_ninja/static/src/js/ks_image_basic_widget.js',
            'ks_dashboard_ninja/static/src/js/ks_import_dashboard.js',
            'ks_dashboard_ninja/static/src/js/ks_quick_edit_view.js',
            'ks_dashboard_ninja/static/src/js/ks_to_do_dashboard.js',
            'ks_dashboard_ninja/static/src/js/ks_to_do_preview.js',
            'ks_dashboard_ninja/static/src/js/ks_widget_toggle.js',
        ],
        # Ensure early availability of client action registration in frontend
        'web.assets_web': [
            'ks_dashboard_ninja/static/src/js/ks_boot.js',
            'ks_dashboard_ninja/static/src/js/ks_dashboard_ninja.js',
            'ks_dashboard_ninja/static/src/js/ks_import_dashboard.js',
        ],
        'web.assets_qweb': [
            'ks_dashboard_ninja/static/src/xml/ks_dashboard_ninja_item_templates.xml',
            'ks_dashboard_ninja/static/src/xml/ks_dashboard_ninja_item_theme.xml',
            'ks_dashboard_ninja/static/src/xml/ks_dashboard_ninja_templates.xml',
            'ks_dashboard_ninja/static/src/xml/ks_dashboard_pro.xml',
            'ks_dashboard_ninja/static/src/xml/ks_dn_global_filter.xml',
            'ks_dashboard_ninja/static/src/xml/ks_quick_edit_view.xml',
            'ks_dashboard_ninja/static/src/xml/ks_to_do_template.xml',
            'ks_dashboard_ninja/static/src/xml/ks_widget_toggle.xml',
        ],
    },
    'data': [
        'security/ir.model.access.csv',
        'security/ks_security_groups.xml',
        'data/ks_default_data.xml',
        'views/ks_dashboard_ninja_view.xml',
        'views/ks_dashboard_ninja_item_view.xml',
        'views/ks_dashboard_action.xml',
        'views/ks_import_dashboard_view.xml',
    ],
    'license': "LGPL-3",
    'installable': True,
    'auto_install': False,
}

