# -*- coding: utf-8 -*-
{
    'name': "Petty Cash",
    'version': "18.0.1.0.0",
    'summary': "Enhanced Petty Cash module",
    'description': "Enhanced Petty Cash module for Odoo 18.0 by roottbar",
    'category': "Uncategorized",
    'author': "Crevisoft",
    'maintainer': "roottbar",
    'depends': [
        'base',
        'board',
        'stock',
        'account_accountant',
        'project',
        'account_check_printing',
        'attachment_indexation',
        'accounting_category_partner',
        'base_dynamic_reports',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'wizard/approved_rejected_request_feeding_view.xml',
        'wizard/approved_cancel_petty_cash_request_view.xml',
        'wizard/petty_cash_request_line_view.xml',
        'wizard/accounts_petty_cash_line_config_view.xml',
        'wizard/products_petty_cash_line_config_view.xml',
        'wizard/analytic_accounts_petty_cash_line_config_view.xml',
        'wizard/partners_petty_cash_line_config_view.xml',
        'wizard/petty_cash_transfer_view.xml',
        'views/dynamic_report_petty_cash_lines.xml',
        'views/dynamic_report_request_feeding.xml',
        'views/partner_view.xml',
        'views/petty_cash_line_view.xml',
        'views/petty_cash_view.xml',
        'views/petty_cash_user_rule_view.xml',
        'views/account_move_view.xml',
        'views/account_payment_view.xml',
        'views/petty_cash_request_feeding_view.xml',
        'views/petty_cash_request_view.xml',
        'views/payment_voucher_view.xml',
        'views/res_partner_account_category_views.xml',
        'views/petty_cash_dashboard_view.xml',
        'views/res_config_view.xml',
        'views/petty_cash_report.xml',
        'views/templates.xml',
        'views/menu_petty_cash.xml',
        'data/data.xml',
        'report/report_petty_cash.xml',
        'report/report_petty_cash_lines.xml',
        'report/request_feeding_report.xml',
        'report/report_payment_voucher.xml',
    ],
    'license': "LGPL-3",
    'installable': False,
    'auto_install': False,
}