# -*- coding: utf-8 -*-
{
    'name': "Dynamic Financial Reports",
    'version': "18.0.1.0.0",
    'summary': "Enhanced Dynamic Financial Reports module",
    'description': "Enhanced Dynamic Financial Reports module for Odoo 18.0 by roottbar",
    'category': "Accounting",
    'author': "Cybrosys Techno Solutions",
    'maintainer': "roottbar",
    'depends': [
        'base',
        'base_accounting_kit',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/templates.xml',
        'views/views.xml',
        'views/kit_menus.xml',
        'report/trial_balance.xml',
        'report/general_ledger.xml',
        'report/cash_flow_report.xml',
        'report/financial_report_template.xml',
        'report/partner_ledger.xml',
        'report/ageing.xml',
        'report/daybook.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'dynamic_accounts_report/static/src/css/report.css',
            'dynamic_accounts_report/static/src/js/action_manager.js',
            'dynamic_accounts_report/static/src/js/ageing.js',
            'dynamic_accounts_report/static/src/js/cash_flow.js',
            'dynamic_accounts_report/static/src/js/daybook.js',
            'dynamic_accounts_report/static/src/js/financial_reports.js',
            'dynamic_accounts_report/static/src/js/general_ledger.js',
            'dynamic_accounts_report/static/src/js/partner_ledger.js',
            'dynamic_accounts_report/static/src/js/trial_balance.js',
        ],
        'web.assets_qweb': [
            'dynamic_accounts_report/static/src/xml/ageing.xml',
            'dynamic_accounts_report/static/src/xml/cash_flow_view.xml',
            'dynamic_accounts_report/static/src/xml/daybook.xml',
            'dynamic_accounts_report/static/src/xml/financial_reports_view.xml',
            'dynamic_accounts_report/static/src/xml/general_ledger_view.xml',
            'dynamic_accounts_report/static/src/xml/partner_ledger_view.xml',
            'dynamic_accounts_report/static/src/xml/trial_balance_view.xml',
        ],
    },
    'license': "LGPL-3",
    'application': True,
    'installable': True,
    'auto_install': False,
}