{
    "name": "Purchase Request",
    "version": "15.0.1.1.1",
    "category": "Purchase Management",
    "depends": ["purchase", "product", "purchase_stock"],
    "data": [
        "security/purchase_request.xml",
        "security/ir.model.access.csv",
        "data/purchase_request_sequence.xml",
        "data/purchase_request_data.xml",
        "reports/report_purchase_request.xml",
        "wizard/purchase_request_line_make_purchase_order_view.xml",
        "views/purchase_request_view.xml",
        "views/purchase_requisition.xml",
        "views/purchase_request_line_view.xml",
        "views/purchase_request_report.xml",
        "views/product_template.xml",
        "views/purchase_order_view.xml",
        "views/stock_move_views.xml",
        "views/stock_picking_views.xml",
        "views/res_config_setting.xml",
    ],
    "license": "LGPL-3",
    "installable": True,
    "application": True,
}
