# -*- coding: utf-8 -*-
{
    'name': "Purchase Request",
    'version': "18.0.1.0.0",
    'summary': "Enhanced Purchase Request module",
    'description': "Enhanced Purchase Request module for Odoo 18.0 by roottbar",
    'category': "Purchase Management",
    'author': "ForgeFlow, Odoo Community Association (OCA)",
    'maintainer': "roottbar",
    'depends': [
        'base',
        'purchase',
        'product',
        'purchase_stock',
    ],
    'data': [
        'security/purchase_request.xml',
        'security/ir.model.access.csv',
        'data/purchase_request_sequence.xml',
        'data/purchase_request_data.xml',
        'reports/report_purchase_request.xml',
        'wizard/purchase_request_line_make_purchase_order_view.xml',
        'views/purchase_request_view.xml',
        'views/purchase_requisition.xml',
        'views/purchase_request_line_view.xml',
        'views/purchase_request_report.xml',
        'views/product_template.xml',
        'views/purchase_order_view.xml',
        'views/stock_move_views.xml',
        'views/stock_picking_views.xml',
    ],
    'license': "LGPL-3",
    'installable': False,
    'auto_install': False,
}