# -*- coding: utf-8 -*-
{
    'name': "HR Customization BSTT",
    'version': "18.0.1.0.0",
    'summary': "Enhanced HR Customization BSTT module",
    'description': "Enhanced HR Customization BSTT module for Odoo 18.0 by roottbar",
    'category': "hr",
    'author': "BSTT company",
    'maintainer': "roottbar",
    'depends': [
        'base',
        'hr',
        'hr_contract',
        'project',
        'bstt_account_invoice',
        'hr_holidays',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'security/security_rules.xml',
        'data/ir_sequence.xml',
        'data/data.xml',
        'data/medical_insurance_type_data.xml',
        'views/hr.xml',
        'views/hr_department_views.xml',
        'views/hr_contract_views.xml',
        'views/hr_work_location_views.xml',
        'views/hr_start_work_views.xml',
        'views/hr_leave_views.xml',
        'views/hr_travel_views.xml',
        'reports/start_work_report_templates.xml',
    ],
    'license': "LGPL-3",
    'installable': False,
    'auto_install': False,
}
