# -*- coding: utf-8 -*-
{
    'name': "Multiple Branch Unit Operation Setup for All Applications Odoo",
    'version': "18.0.1.0.0",
    'summary': "Enhanced Multiple Branch Unit Operation Setup for All Applications Odoo module",
    'description': "Enhanced Multiple Branch Unit Operation Setup for All Applications Odoo module for Odoo 18.0 by roottbar",
    'category': "Sales",
    'author': "BrowseInfo",
    'maintainer': "roottbar",
    'depends': [
        'base',
        'sale_management',
        'purchase',
        'stock',
        'account',
        'purchase_stock',
        'web',
    ],
    'data': [
        'security/branch_security.xml',
        'security/multi_branch.xml',
        'security/ir.model.access.csv',
        'reports/account_invoice_report_view.xml',
        'views/res_branch_view.xml',
        'views/inherited_res_users.xml',
        'views/inherited_sale_order.xml',
        'views/inherited_stock_picking.xml',
        'views/inherited_stock_move.xml',
        'views/inherited_account_invoice.xml',
        'views/inherited_purchase_order.xml',
        'views/inherited_stock_warehouse.xml',
        'views/inherited_stock_location.xml',
        'views/inherited_account_bank_statement.xml',
        'wizard/inherited_account_payment.xml',
        'views/inherited_stock_inventory.xml',
        'views/inherited_product.xml',
        'views/inherited_partner.xml',
        'views/stock_quant_views.xml',
        'views/stock_valuation_layer_views.xml',
    ],
    'license': "LGPL-3",
    'application': True,
    'installable': True,
    'auto_install': False,
}