{
    'name': 'Budget Management',
    'version': '15.0.1.0.0',
    'summary': 'إدارة الميزانيات للأقسام والمشاريع مع ربط المشتريات',
    'description': 'موديول لإعداد ميزانيات الأقسام والمشاريع والتحقق منها قبل اعتماد أوامر الشراء وتحديث المصروفات وعرض تقارير.',
    'category': 'Accounting/Purchases',
    'author': 'Othmancs',
    'license': 'OPL-1',
    'depends': ['purchase', 'account'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/department_views.xml',
        'views/project_views.xml',
        'views/budget_views.xml',
        'views/purchase_order_views.xml',
        'views/account_move_views.xml',
        'report/budget_report.xml',
        'report/budget_report_templates.xml',
    ],
    'application': True,
    'installable': True,
}