# -*- coding: utf-8 -*-
{
    'name': "HR Resume ATS Analysis",
    'version': "18.0.1.0.0",
    'summary': "Enhanced HR Resume ATS Analysis module",
    'description': "Enhanced HR Resume ATS Analysis module for Odoo 18.0 by roottbar",
    'category': "Human Resources",
    'author': "Your Company",
    'maintainer': "roottbar",
    'depends': [
        'base',
        'hr',
        'hr_recruitment',
        'mail',
        'portal',
        'web',
    ],
    'data': [
        'security/hr_resume_ats_security.xml',
        'security/ir.model.access.csv',
        'data/module_data.xml',
        'views/hr_resume_analysis_views.xml',
        'views/hr_job_position_views.xml',
        'views/res_config_settings_views.xml',
        'views/hr_resume_ats_menus.xml',
        'reports/resume_analysis_report.xml',
    ],
    'license': "LGPL-3",
    'installable': False,
    'auto_install': False,
}