# -*- coding: utf-8 -*-
{
    'name': "Project Advanced",
    'version': "18.0.1.0.0",
    'summary': "Enhanced Project Advanced module",
    'description': "Enhanced Project Advanced module for Odoo 18.0 by roottbar",
    'category': "hidden",
    'author': "Crevisoft",
    'maintainer': "roottbar",
    'depends': [
        'base',
        'project_forecast',
        'project_enterprise',
        'hr_contract',
        'hr_timesheet',
        'web_dashboard',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/sequence.xml',
        'views/project_views.xml',
        'views/project_task.xml',
        'views/project_template_views.xml',
        'views/project_task_type.xml',
        'views/res_config_settings.xml',
        'wizard/change_allow_user_task_view.xml',
        'wizard/task_assign_history_wizard_view.xml',
    ],
    'license': "LGPL-3",
    'installable': False,
    'auto_install': False,
}